---
- :code: 401
  :string_code: unauthenticated
  :label: access_token_required
- :code: 401
  :string_code: unauthenticated
  :label: sign_required
- :code: 401
  :string_code: unauthenticated
  :label: token_required
- :code: 401
  :string_code: unauthenticated
  :label: invalid_sign
- :code: 401
  :string_code: unauthenticated
  :label: invalid_or_expired_access_token
- :code: 401
  :string_code: unauthenticated
  :label: user_is_not_authorized_for_access_token
- :code: 403
  :string_code: unauthorized
  :label: pin_not_found_or_expired
- :code: 403
  :string_code: unauthorized
  :label: invalid_pin
- :code: 403
  :string_code: unauthorized
  :label: pin_required
- :code: 403
  :string_code: unauthorized
  :label: pin_already_confirmed
- :code: 403
  :string_code: unauthorized
  :label: pin_cannot_be_confirmed
- :code: 403
  :string_code: unauthorized
  :label: unauthorized
- :code: 403
  :string_code: unauthorized
  :label: device_id_required
- :code: 403
  :string_code: unauthorized
  :label: user_agent_required
- :code: 403
  :string_code: unauthorized
  :label: email_or_phone_required
- :code: 403
  :string_code: unauthorized
  :label: password_required
- :code: 403
  :string_code: unauthorized
  :label: user_by_email_doesnt_exist
- :code: 403
  :string_code: unauthorized
  :label: user_by_phone_doesnt_exist
- :code: 403
  :string_code: unauthorized
  :label: invalid_password
- :code: 404
  :string_code: record_not_found
  :label: user_not_found
- :code: 404
  :string_code: record_not_found
  :label: record_not_found
- :code: 422
  :string_code: unprocessible_entity
  :label: phone_dont_match_as_requested
- :code: 422
  :string_code: unprocessible_entity
  :label: email_dont_match_as_requested
- :code: 422
  :string_code: unprocessible_entity
  :label: user_has_not_enough_rights
- :code: 422
  :string_code: unprocessible_entity
  :label: x_user_id_required
- :code: 422
  :string_code: unprocessible_entity
  :label: new_password_cant_be_as_old
- :code: 422
  :string_code: unprocessible_entity
  :label: invalid_old_password
- :code: 422
  :string_code: unprocessible_entity
  :label: pin_cannot_be_created
- :code: 422
  :string_code: record_invalid
  :label: record_invalid
- :code: 422
  :string_code: unprocessible_entity
  :label: unprocessible_entity
- :code: 422
  :string_code: unprocessible_entity
  :label: invalid_email_format
- :code: 422
  :string_code: unprocessible_entity
  :label: invalid_phone_format
- :code: 422
  :string_code: unprocessible_entity
  :label: email_already_in_use
- :code: 422
  :string_code: unprocessible_entity
  :label: phone_already_in_use
- :code: 422
  :string_code: unprocessible_entity
  :label: email_not_confirmed
- :code: 422
  :string_code: unprocessible_entity
  :label: phone_not_confirmed
- :code: 422
  :string_code: unprocessible_entity
  :label: email_not_match
- :code: 422
  :string_code: unprocessible_entity
  :label: phone_not_match
- :code: 422
  :string_code: unprocessible_entity
  :label: email_required
- :code: 422
  :string_code: unprocessible_entity
  :label: phone_required
- :code: 422
  :string_code: unprocessible_entity
  :label: facebook_token_required
- :code: 422
  :string_code: unprocessible_entity
  :label: google_token_required
